# Generated by Django 4.1.1 on 2022-11-19 02:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='about',
            options={'verbose_name': 'Биз жонундо', 'verbose_name_plural': 'Биз жонундо'},
        ),
    ]
