# Generated by Django 4.1.2 on 2022-11-18 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AcreditationList1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='acreditation/', verbose_name='Аккредитация файлы')),
                ('name', models.CharField(max_length=255, verbose_name='Аты')),
            ],
            options={
                'verbose_name': 'Институциалдык аккредитация',
                'verbose_name_plural': 'Институциалдык аккредитация',
            },
        ),
    ]
