# Generated by Django 4.1.1 on 2022-11-18 13:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accreditation1', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='acreditationlist1',
            name='file',
        ),
    ]
