# Generated by Django 4.1.1 on 2022-11-18 17:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accreditation1', '0002_remove_acreditationlist1_file'),
    ]

    operations = [
        migrations.CreateModel(
            name='AcreditationList1Detail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accreditation_detail', models.FileField(upload_to='accreditation/', verbose_name='Документ файл')),
                ('name', models.CharField(max_length=255, verbose_name='Аты')),
                ('accreditation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accreditation', to='accreditation1.acreditationlist1', verbose_name='Аккредитация')),
            ],
            options={
                'verbose_name': 'Институциалдык аккредитация',
                'verbose_name_plural': 'Институциалдык аккредитация',
            },
        ),
    ]
