# Generated by Django 4.1.1 on 2022-11-18 18:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accreditation1', '0003_acreditationlist1detail'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='acreditationlist1detail',
            options={'verbose_name': 'Институциалдык аккредитация болумго киргизуу', 'verbose_name_plural': 'Институциалдык аккредитация болумго киргизуу'},
        ),
    ]
