# Generated by Django 4.1.2 on 2022-10-31 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Settings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_site', models.CharField(max_length=255, verbose_name='Мектпетин аты')),
                ('desc_site', models.TextField(verbose_name='Мектеп боюнча маалымат')),
                ('logo_site', models.ImageField(upload_to='logo/', verbose_name='Мектептин Суроту')),
            ],
            options={
                'verbose_name': 'Мектеп боюнча',
                'verbose_name_plural': 'Мектеп',
            },
        ),
    ]
