# Generated by Django 4.1.2 on 2022-11-01 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Slide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Текст')),
                ('desc', models.TextField(verbose_name='Кошумча маалымат.')),
                ('image', models.ImageField(upload_to='slide/', verbose_name='Суроту')),
            ],
            options={
                'verbose_name': 'Слайдтар',
                'verbose_name_plural': 'Слайдтар',
            },
        ),
    ]
