# Generated by Django 4.1.2 on 2022-11-01 12:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0002_slide'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Slide',
        ),
    ]
