# Generated by Django 4.1.2 on 2022-11-01 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0004_settings_desc2_site'),
    ]

    operations = [
        migrations.AddField(
            model_name='settings',
            name='slide_site',
            field=models.ImageField(default=1, upload_to='slide/', verbose_name='Слайд'),
            preserve_default=False,
        ),
    ]
