# Generated by Django 4.1.2 on 2022-11-01 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0005_settings_slide_site'),
    ]

    operations = [
        migrations.CreateModel(
            name='Slide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slide_site', models.CharField(max_length=255, verbose_name='Сурот киргизуу')),
            ],
            options={
                'verbose_name': 'Слайдтар',
                'verbose_name_plural': 'Слайдтар',
            },
        ),
    ]
