# Generated by Django 4.1.2 on 2022-11-01 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0006_slide'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='slide',
            name='slide_site',
        ),
        migrations.AddField(
            model_name='slide',
            name='slide10_site',
            field=models.ImageField(default=1, upload_to='slides/', verbose_name='10-слайд'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='slide',
            name='slide1_site',
            field=models.ImageField(default=1, upload_to='slides/', verbose_name='1-слайд'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='slide',
            name='slide2_site',
            field=models.ImageField(default=1, upload_to='slides/', verbose_name='2-слайд'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='slide',
            name='slide3_site',
            field=models.ImageField(default=1, upload_to='slides/', verbose_name='3-слайд'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='slide',
            name='slide4_site',
            field=models.ImageField(default=1, upload_to='slides/', verbose_name='4-слайд'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='slide',
            name='slide5_site',
            field=models.ImageField(default=1, upload_to='slides/', verbose_name='5-слайд'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='slide',
            name='slide6_site',
            field=models.ImageField(default=1, upload_to='slides/', verbose_name='6-слайд'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='slide',
            name='slide7_site',
            field=models.ImageField(default=1, upload_to='slides/', verbose_name='7-слайд'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='slide',
            name='slide8_site',
            field=models.ImageField(default=1, upload_to='slides/', verbose_name='8-слайд'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='slide',
            name='slide9_site',
            field=models.ImageField(default=1, upload_to='slides/', verbose_name='9-слайд'),
            preserve_default=False,
        ),
    ]
