# Generated by Django 4.1.2 on 2022-11-03 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0007_remove_slide_slide_site_slide_slide10_site_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lessons',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='lesson/', verbose_name='Сабактын суроту')),
                ('name', models.CharField(max_length=255, verbose_name='Сабактын аты')),
            ],
            options={
                'verbose_name': 'Сабактар',
                'verbose_name_plural': 'Сабактар',
            },
        ),
    ]
