# Generated by Django 4.1.2 on 2022-11-03 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0009_lessons_teacher'),
    ]

    operations = [
        migrations.AddField(
            model_name='lessons',
            name='teacher_image',
            field=models.ImageField(default=1, upload_to='teacher/', verbose_name='Мугалимдин суроту'),
            preserve_default=False,
        ),
    ]
