# Generated by Django 4.1.2 on 2022-11-03 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0010_lessons_teacher_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Title',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Болумдун аты')),
                ('desc', models.TextField(verbose_name='Болум боюнча маалымат')),
            ],
            options={
                'verbose_name': 'Болум',
                'verbose_name_plural': 'Болум',
            },
        ),
    ]
