# Generated by Django 4.1.1 on 2022-11-19 02:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0012_remove_title_desc_remove_title_name_title_desc1_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Lessons',
        ),
    ]
