# Generated by Django 4.1.2 on 2022-11-07 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='teacher/', verbose_name='Мугалимдин суроту')),
                ('name', models.CharField(max_length=255, verbose_name='Мугалимдин аты-жону')),
                ('work', models.CharField(max_length=255, verbose_name='Мугалимдин иши')),
                ('year', models.CharField(max_length=255, verbose_name='Мугалимдин туулган жылы')),
                ('edu', models.TextField(verbose_name='Мугалимдин Билими')),
                ('oput', models.CharField(max_length=255, verbose_name='Мугалимдин тажрыйбасы')),
                ('number', models.CharField(max_length=255, verbose_name='Мугалимдин номери')),
                ('email', models.CharField(max_length=255, verbose_name='Мугалимдин почтасы')),
                ('facebook', models.URLField(verbose_name='Мугалимдин Facebook баракчасы')),
                ('instagram', models.URLField(verbose_name='Мугалимдин Instagram баракчасы')),
                ('whatsapp', models.URLField(verbose_name='Мугалимдин WhatsApp баракчасы')),
            ],
        ),
    ]
