# Generated by Django 4.1.2 on 2022-11-07 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='desc',
            field=models.TextField(default=1, verbose_name='Мугалим жонундо маалымат'),
            preserve_default=False,
        ),
    ]
