# Generated by Django 4.1.2 on 2022-11-07 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0002_teacher_desc'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='teacher',
            options={'verbose_name': 'Мугалимдер', 'verbose_name_plural': 'Мугалимдер'},
        ),
        migrations.AlterField(
            model_name='teacher',
            name='edu',
            field=models.TextField(verbose_name='Мугалимдин окуган жери'),
        ),
    ]
