# Generated by Django 4.1.2 on 2022-11-07 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Class',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='class/', verbose_name='Класстын суроту')),
                ('name', models.CharField(max_length=255, verbose_name='Класстын аты')),
                ('prod', models.CharField(max_length=244, verbose_name='Класстын графиги')),
                ('teacher', models.CharField(max_length=255, verbose_name='Класс жетекчиси')),
                ('teacher_image', models.ImageField(upload_to='class_teacher/', verbose_name='Класс жетекчинин суроту')),
            ],
            options={
                'verbose_name': 'Класстар',
                'verbose_name_plural': 'Класстар',
            },
        ),
    ]
