# Generated by Django 4.1.2 on 2022-11-08 13:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('classs', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Class',
            new_name='Classe',
        ),
    ]
