# Generated by Django 4.1.2 on 2022-11-08 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classs', '0002_rename_class_classe'),
    ]

    operations = [
        migrations.AddField(
            model_name='classe',
            name='prod1',
            field=models.CharField(default=1, max_length=244, verbose_name='Класстын кунумдук графиги'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='classe',
            name='prod',
            field=models.CharField(max_length=244, verbose_name='Класстын жумалык графиги'),
        ),
    ]
